/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVerifyOtpRouteImport } from './routes/api/verify-otp'
import { Route as ApiRequestOtpRouteImport } from './routes/api/request-otp'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyOtpRoute = ApiVerifyOtpRouteImport.update({
  id: '/api/verify-otp',
  path: '/api/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestOtpRoute = ApiRequestOtpRouteImport.update({
  id: '/api/request-otp',
  path: '/api/request-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/request-otp': typeof ApiRequestOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/request-otp': typeof ApiRequestOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/request-otp': typeof ApiRequestOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/logout'
    | '/api/request-otp'
    | '/api/verify-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/logout'
    | '/api/request-otp'
    | '/api/verify-otp'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/logout'
    | '/api/request-otp'
    | '/api/verify-otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiRequestOtpRoute: typeof ApiRequestOtpRoute
  ApiVerifyOtpRoute: typeof ApiVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-otp': {
      id: '/api/verify-otp'
      path: '/api/verify-otp'
      fullPath: '/api/verify-otp'
      preLoaderRoute: typeof ApiVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-otp': {
      id: '/api/request-otp'
      path: '/api/request-otp'
      fullPath: '/api/request-otp'
      preLoaderRoute: typeof ApiRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiRequestOtpRoute: ApiRequestOtpRoute,
  ApiVerifyOtpRoute: ApiVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
