/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWavesRouteImport } from './routes/dashboard/waves'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardQueueRouteImport } from './routes/dashboard/queue'
import { Route as DashboardPushLogRouteImport } from './routes/dashboard/push-log'
import { Route as DashboardMatchingRouteImport } from './routes/dashboard/matching'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard/groups'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard/conversations'
import { Route as ApiVerifyOtpRouteImport } from './routes/api/verify-otp'
import { Route as ApiRequestOtpRouteImport } from './routes/api/request-otp'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWavesRoute = DashboardWavesRouteImport.update({
  id: '/waves',
  path: '/waves',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPushLogRoute = DashboardPushLogRouteImport.update({
  id: '/push-log',
  path: '/push-log',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMatchingRoute = DashboardMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiVerifyOtpRoute = ApiVerifyOtpRouteImport.update({
  id: '/api/verify-otp',
  path: '/api/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestOtpRoute = ApiRequestOtpRouteImport.update({
  id: '/api/request-otp',
  path: '/api/request-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/request-otp': typeof ApiRequestOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/matching': typeof DashboardMatchingRoute
  '/dashboard/push-log': typeof DashboardPushLogRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/waves': typeof DashboardWavesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/request-otp': typeof ApiRequestOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/matching': typeof DashboardMatchingRoute
  '/dashboard/push-log': typeof DashboardPushLogRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/waves': typeof DashboardWavesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/request-otp': typeof ApiRequestOtpRoute
  '/api/verify-otp': typeof ApiVerifyOtpRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/dashboard/matching': typeof DashboardMatchingRoute
  '/dashboard/push-log': typeof DashboardPushLogRoute
  '/dashboard/queue': typeof DashboardQueueRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/waves': typeof DashboardWavesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/logout'
    | '/api/request-otp'
    | '/api/verify-otp'
    | '/dashboard/conversations'
    | '/dashboard/groups'
    | '/dashboard/matching'
    | '/dashboard/push-log'
    | '/dashboard/queue'
    | '/dashboard/users'
    | '/dashboard/waves'
    | '/dashboard/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/logout'
    | '/api/request-otp'
    | '/api/verify-otp'
    | '/dashboard/conversations'
    | '/dashboard/groups'
    | '/dashboard/matching'
    | '/dashboard/push-log'
    | '/dashboard/queue'
    | '/dashboard/users'
    | '/dashboard/waves'
    | '/dashboard'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/logout'
    | '/api/request-otp'
    | '/api/verify-otp'
    | '/dashboard/conversations'
    | '/dashboard/groups'
    | '/dashboard/matching'
    | '/dashboard/push-log'
    | '/dashboard/queue'
    | '/dashboard/users'
    | '/dashboard/waves'
    | '/dashboard/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiRequestOtpRoute: typeof ApiRequestOtpRoute
  ApiVerifyOtpRoute: typeof ApiVerifyOtpRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/waves': {
      id: '/dashboard/waves'
      path: '/waves'
      fullPath: '/dashboard/waves'
      preLoaderRoute: typeof DashboardWavesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queue': {
      id: '/dashboard/queue'
      path: '/queue'
      fullPath: '/dashboard/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/push-log': {
      id: '/dashboard/push-log'
      path: '/push-log'
      fullPath: '/dashboard/push-log'
      preLoaderRoute: typeof DashboardPushLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/matching': {
      id: '/dashboard/matching'
      path: '/matching'
      fullPath: '/dashboard/matching'
      preLoaderRoute: typeof DashboardMatchingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/verify-otp': {
      id: '/api/verify-otp'
      path: '/api/verify-otp'
      fullPath: '/api/verify-otp'
      preLoaderRoute: typeof ApiVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-otp': {
      id: '/api/request-otp'
      path: '/api/request-otp'
      fullPath: '/api/request-otp'
      preLoaderRoute: typeof ApiRequestOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardGroupsRoute: typeof DashboardGroupsRoute
  DashboardMatchingRoute: typeof DashboardMatchingRoute
  DashboardPushLogRoute: typeof DashboardPushLogRoute
  DashboardQueueRoute: typeof DashboardQueueRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWavesRoute: typeof DashboardWavesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardGroupsRoute: DashboardGroupsRoute,
  DashboardMatchingRoute: DashboardMatchingRoute,
  DashboardPushLogRoute: DashboardPushLogRoute,
  DashboardQueueRoute: DashboardQueueRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWavesRoute: DashboardWavesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiRequestOtpRoute: ApiRequestOtpRoute,
  ApiVerifyOtpRoute: ApiVerifyOtpRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
