/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as ChildSafetyRouteImport } from './routes/child-safety'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildSafetyRoute = ChildSafetyRouteImport.update({
  id: '/child-safety',
  path: '/child-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/child-safety': typeof ChildSafetyRoute
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/child-safety': typeof ChildSafetyRoute
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/child-safety': typeof ChildSafetyRoute
  '/pitch': typeof PitchRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/child-safety'
    | '/pitch'
    | '/privacy'
    | '/product'
    | '/terms'
    | '/join/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/child-safety'
    | '/pitch'
    | '/privacy'
    | '/product'
    | '/terms'
    | '/join/$code'
  id:
    | '__root__'
    | '/'
    | '/child-safety'
    | '/pitch'
    | '/privacy'
    | '/product'
    | '/terms'
    | '/join/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildSafetyRoute: typeof ChildSafetyRoute
  PitchRoute: typeof PitchRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  TermsRoute: typeof TermsRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child-safety': {
      id: '/child-safety'
      path: '/child-safety'
      fullPath: '/child-safety'
      preLoaderRoute: typeof ChildSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildSafetyRoute: ChildSafetyRoute,
  PitchRoute: PitchRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  TermsRoute: TermsRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
